let invalid_url = lang === 'en' ? 'Invalid URL' : 'URL Tidak Valid';
let invalid_number = lang === 'en' ? 'Value should be more than 0' : 'Nilai harus lebih dari 0';
let label_pageName1 = lang === 'en' ? 'Page' : 'Laman';
let label_pageName2 = lang === 'en' ? 'name' : 'nama';
let placeholder_pageName = lang === 'en' ? 'Type your page name here..' : 'Ketik nama halaman Anda di sini ...';
let placeholder_pageUrl = lang === 'en' ? 'Type your page URL here..' : 'Ketik URL halaman Anda di sini ...';
let label_question = lang === 'en' ? 'Question' : 'Pertanyaan';
let label_answer = lang === 'en' ? 'Answer' : 'Jawaban';
let placeholder_question = lang === 'en' ? 'Type your question here..' : 'Ketik pertanyaan Anda di sini..';
let placeholder_answer = lang === 'en' ? 'Type your answer here..' : 'Ketik jawaban Anda di sini..';
let label_instructions1 = lang === 'en' ? 'Step' : 'Langkah';
let label_instructions2 = lang === 'en' ? 'instruction' : 'instruksi';
let label_image = lang === 'en' ? 'Image URL' : 'URL Gambar';
let label_name = lang === 'en' ? 'Name' : 'Nama';
let placeholder_supplyTool1 = lang === 'en' ? 'Type' : 'Ketik';
let placeholder_supplyTool2 = lang === 'en' ? 'here..' : 'di sini..';
let placeholder_instructions = lang === 'en' ? 'Type your instruction here..' : 'Ketik instruksi Anda di sini..';
let placeholder_image = lang === 'en' ? 'Type image URL here..' : 'Ketik URL gambar di sini..';
let placeholder_name = lang === 'en' ? 'Type name here..' : 'Ketik nama di sini..';
let placeholder_urlStep = lang === 'en' ? 'Type URL here..' : 'Ketik URL di sini..';
let placeholder_sosmedUrl1 = lang === 'en' ? 'Type your' : 'Ketik URL';
let placeholder_sosmedUrl2 = lang === 'en' ? 'URL here..' : 'Anda di sini..';
let label_ingredients = lang === 'en' ? 'Ingredients' : 'Bahan';
let label_text = lang === 'en' ? 'Text' : 'Teks';
let label_review_name = lang === 'en' ? 'Review’s name' : 'Nama Ulasan';
let label_review_body = lang === 'en' ? 'Review’s body' : 'Isi Ulasan';
let label_review_rating = lang === 'en' ? 'Rating' : 'Peringkat';
let label_review_date = lang === 'en' ? 'Date' : 'Tanggal';
let label_review_author = lang === 'en' ? 'Author' : 'Penulis';
let label_review_publisher = lang === 'en' ? 'Publisher' : 'Penerbit';
let placeholder_ingredients = lang === 'en' ? 'Type ingredient here..' : 'Ketik bahan disini..';
let placeholder_step = lang === 'en' ? 'Type step here..' : 'Ketik langkah di sini..';
let placeholder_review_name = lang === 'en' ? 'Type review\'s name here..' : 'Ketik nama ulasan disini..';
let placeholder_review_body = lang === 'en' ? 'Type review\'s body here..' : 'Ketik isi ulasan disini..';
let placeholder_review_date = lang === 'en' ? 'Pick a date' : 'Pilih tanggal';
let placeholder_review_author = lang === 'en' ? 'Type author name here..' : 'Ketik nama penulis disini..';
let placeholder_review_publisher = lang === 'en' ? 'Type publisher here..' : 'Ketik penerbit disini';
let step = lang === 'en' ? 'Step' : 'Langkah Langkah';
let created_at = lang === 'en' ? 'Created at ' : 'Dibuat pada ';
let localStorageNone = lang === 'en' ? 'This is your first impressions, no history yet!' : 'Ini adalah kesan pertama Anda, belum ada riwayat!';
let placeholder_access = lang === 'en' ? 'Select access' : 'Pilih akses';
let access_opt_1 = lang === 'en' ? 'Allow' : 'Izinkan';
let access_opt_2 = lang === 'en' ? 'Disallow' : 'Jangan izinkan';
let placeholder_user_agent = lang === 'en' ? 'Select user agent' : 'Pilih agen pengguna';
let placeholder_directory = lang === 'en' ? 'your-directory' : 'direktori-anda';
let robot_sleep = lang === 'en' ? 'Our robot is sleeping right now. Give him a task!' : 'Robot kita sedang tidur sekarang. Beri dia tugas!';
let robot_progress = lang === 'en' ? 'Our robot is excecuting your task..' : 'Robot kami sedang menjalankan tugas Anda ...';
let robot_done = lang === 'en' ? 'Our robot is already finished your task.' : 'Robot kami sudah menyelesaikan tugas Anda.';
let has_crawled = lang === 'en' ? ' Has been crawled' : ' Telah ditelusuri';
let show_more = lang === 'en' ? 'Show More' : 'Tampilkan Lebih Banyak';
let btn_download = lang === 'en' ? 'Download Sitemap' : 'Unduh Sitemap';
let btn_cancel = lang === 'en' ? 'Cancel' : 'Batal';
let title_friendly = lang === 'en' ? 'Page is mobile friendly' : 'Halaman mobile friendly';
let subtitle_friendly = lang === 'en' ? 'This page is easy to use on a mobile device' : 'Halaman ini mudah digunakan di perangkat seluler';
let title_unspecified = lang === 'en' ? 'An Error Occurred While Performing a Test. Please Try Again' : 'Terjadi Kesalahan Saat Melakukan Tes. Silakan Coba Lagi';
let title_not_friendly = lang === 'en' ? 'Page is not mobile friendly' : 'Halaman tidak mobile friendly';
let subtitle_not_friendly = lang === 'en' ? 'This page is difficult to use on a mobile device' : 'Halaman ini tidak mudah digunakan di perangkat seluler';
let mob_wider = lang === 'en' ? 'Content wider than screen' : 'Konten lebih lebar dari layar';
let mob_unexpected = lang === 'en' ? 'Sorry, we don\'t have a description of the settings for errors.' : 'Maaf, kami tidak memiliki deskripsi tentang pengaturan untuk kesalahan.';
let mob_plugin = lang === 'en' ? 'Uses incompatible plugins' : 'Menggunakan plugin yang tidak cocok   ';
let mob_viewnot = lang === 'en' ? 'Viewport not set' : 'Area pandang tidak diatur';
let mob_viewnotto = lang === 'en' ? 'Viewport not set to "device-width"' : 'Area pandang tidak diatur ke lebar perangkat';
let mob_text = lang === 'en' ? 'Text too small to read' : 'Teks terlalu kecil untuk dibaca';
let mob_element = lang === 'en' ? 'Clickable elements too close together' : 'Elemen yang dapat diklik terlalu berdekatan';
let mob_fix = lang === 'en' ? 'Fix the Following Problems' : 'Perbaiki Masalah Berikut';
let test_date = lang === 'en' ? 'Tested on ' : 'Diuji pada ';
let test_time = lang === 'en' ? ' at ' : ' jam ';
