name: staging-deployment

on:
  push:
    branches: [ develop ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest
    steps:
      - name: SSH remote command executer
        # You may pin to the exact commit or the version.
        uses: tarunjangra/ssh-remote-cmd@v1
        with:
          # Command to execute on the remote server.
          command: |
            cd /var/www/staging-FreeTools/
            git stash
            git pull origin develop
            composer install
            chown www-data:www-data -R ./
            chmod 775 -R storage/ public/ bootstrap/cache
          # Hostname or IP address of the server.
          host: ${{secrets.HOST_ADDRESS}}
          # Username for authentication to server.
          user: ${{secrets.HOST_USER}}
          # Port number of the server.
          port: 22
          # File Location or string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          key: ${{secrets.PRIVATE_KEY}}
          # Password for authentication.
          pass: ${{secrets.HOST_PASS}}
